### PR TITLE
fix: patch requests are case-sensitive

### PR DESCRIPTION
**Pull request by semoal**
I've added a test to avoid a regression on this :)
Here it is @developit ;)

### CODE REVIEW

**Comment by semoal** [comment]
@developit Ping on this Jason, don't want to add hurry just pinging to not forget =)

**Comment by lohfu** [comment]
any reason you are not uppercasing all http methods? even if they dont seem to break when lowercase i reckon they should be converted to uppercase both for consistency but more importantly the spec seems to recommend normalizing (converting to uppercase) all methods for backwards compatibility:

https://fetch.spec.whatwg.org/#methods

**Comment by semoal** [comment]
> any reason you are not uppercasing all http methods? even if they dont seem to break when lowercase i reckon they should be converted to uppercase both for consistency but more importantly the spec seems to recommend normalizing (converting to uppercase) all methods for backwards compatibility:
> 
> 
> 
> https://fetch.spec.whatwg.org/#methods

Didn't know that ;) just fixing the wrong use case, but if normalizing is the correct approach I'll modify the PR later, thanks mate

**Comment by sirlancelot** [comment]
In Google Chrome, patch specifically seemed to be causing problems. I'd been Googling for about an hour and finally came across this SO post: https://stackoverflow.com/a/67744766/51021

Apparently, some verbs (`PATCH` in my case) ARE case-sensitive when comparing against a pre-flight `OPTIONS` check.

I think in order to be the most compatible with the `axios` module, and to make `PATCH` work during cross-origin requests, these verbs should be made uppercase (See `axios` source: [axios/lib/adapters/xhr.js#L32](https://github.com/axios/axios/blob/5ad6994/lib/adapters/xhr.js#L32))

**Comment by developit** [comment]
From the size bot:

**Size Change:** +56 B (1%) 

**Total Size:** 3.02 kB

| Filename | Size | Change | |
|:--- |:---:|:---:|:---:|
| `dist/redaxios.js` | 990 B | +18 B (1%) |  |
| `dist/redaxios.module.js` | 990 B | +19 B (1%) |  |
| `dist/redaxios.umd.js` | 1.04 kB | +19 B (1%) |  |


<a href="https://github.com/preactjs/compressed-size-action"><sub>compressed-size-action</sub></a>

**Comment by developit** [comment]
I might try checking if `'get'.toUpperCase()` produces smaller sizes when minified.

**Comment by semoal** [comment]
@googlebot I fixed it.

**Comment by semoal** [comment]
> I might try checking if `'get'.toUpperCase()` produces smaller sizes when minified.

Yep, I think so.

```bash
Build "redaxios" to dist:
        949 B: redaxios.js.gz
        825 B: redaxios.js.br
        945 B: redaxios.module.js.gz
        823 B: redaxios.module.js.br
        997 B: redaxios.umd.js.gz
        871 B: redaxios.umd.js.br
```

Just pushed the change to test against the github workflow.

**Comment by matschik** [comment]
We just encountered the same problem and this PR would fix it 🥳 
Is there anything blocking the merge ?

**Pull request merged**
