### PR TITLE
minimalistic transformResponse for json response type

### PR DESCRIPTION
**Pull request by Arminkhodaei**
Hi,
#21 & maybe #13 could be solved with this PR. I tried to keep it minimal, even though it's not the most generic way to be done.
There should be a minor conflict with my previous PR, but I still preferred to push on separate branches.

### CODE REVIEW

**Comment by Arminkhodaei** [comment]
About exposing `transformResponse` outside of the library, I understand the axios compatibility issues, but I don't find any other reason to do so. As I see it, response interceptors are able to satisfy the same need. Correct me if I'm wrong in this matter, please :)

**Comment by tandrewnichols** [comment]
What's the eta here? Would like to switch to redaxios for size, but I'd prefer not to have to go find every existing usage of axios and make them `JSON.parse` the response data manually.

**Comment by developit** [comment]
Looks good - I believe inlining the transformResponse function will help with file size here (this PR is up 27b, the size bot can't post on fork PRs).

**Comment by Stamper** [comment]
hi guys,
unfortunately redaxios didn't bring JSON object to me in case of Content-Type == application/json, therefore I can't see how [this line](https://github.com/developit/redaxios/pull/26/files#diff-1fdf421c05c1140f6d71444ea2b27638R126) could fix #21 
I'd rather erase that `if (typeof data === 'string')` clause and keep `try JSON.parse(data) catch` itself.

**Pull request merged**
