### PR TITLE
fix: updates error handling to match axios

### PR DESCRIPTION
**Pull request by electricflannel**
Ran into an issue where we are passing the error message as part of the 400/500 body.  The current implementation drops that data, where axios returns the body.

#48

### CODE REVIEW

**Comment by electricflannel** [comment]
@googlebot I signed it!

**Comment by electricflannel** [comment]
@googlebot I signed it!

**Comment by electricflannel** [comment]
@googlebot I fixed it.

**Comment by electricflannel** [comment]
@googlebot I fixed it.

**Comment by electricflannel** [comment]
@developit I was wondering if we could get this merged in?

**Comment by developit** [comment]
Sorry for the delay.

**Review by developit — APPROVED** [review]
Excellent work. Only 3b larger!

**Comment by josuemontano** [comment]
Thanks for the fix! Would it be possible to have an npm release please?

**Comment by gianpaj** [comment]
same here. @developit could you make a release, please? 🙏

**Comment by gianpaj** [comment]
BTW we should add a test, like the one in axios:

`should return JSON when rejecting`
https://github.com/axios/axios/blob/master/test/specs/requests.spec.js#L234

I don't know how to mock an API call that returns an error message with [karmatic](https://github.com/developit/karmatic)
It probably needs to be added to this file:
https://github.com/developit/redaxios/blob/master/test/index.test.js

axios's project is using https://github.com/jasmine/jasmine-ajax - I wonder if need that too

**Pull request merged**
